Arr/add user to circle functionality
aidan-hubley/Prayer-Circle pull request #106
Opened 2024-01-24 01:12 UTC by Statmosphere

**Changes**
Include a short description of your changes

**Notes**
Include any notes you have about your changes, or for the reviewer

**YouTrack Link**
Include the link to the corresponding YouTrack item

2024-01-24 05:35 UTC, aidan-hubley commented on package.json
Why is this here? Pretty sure we don't want this package...

2024-01-24 05:41 UTC, aidan-hubley commented on app/(settings)/circleSettings.js
What happened here? Why is this file edited at all?

2024-01-24 05:44 UTC, aidan-hubley requested changes
Overall it's great, although I don't know why circleSettings was changes... I also don't think we should add that SVG package back...

2024-01-25 17:16 UTC, Statmosphere commented on package.json
It was added when my app wouldn't start. I've removed it and I was able to access the app fine without it.

2024-01-25 17:17 UTC, Statmosphere commented on app/(settings)/circleSettings.js
Leftovers from another branch. I'll probably use this in the future but for the purposes of this pull request I'll remove it.

2024-01-26 22:31 UTC, Statmosphere reviewed
Made all of the changes and added both reloading and checking to see if you're already a member.

2024-01-26 23:55 UTC, aidan-hubley approved these changes
Well done! Looking forward to public codes adding a user to the member queue!

2024-01-27 07:04 UTC, merged